// ISO 3166-1 alpha-2 country codes and names

class Country {
  final String code;
  final String name;

  const Country(this.code, this.name);
}

const countries = <Country>[
  Country('AD', 'Andorra'),
  Country('AE', 'United Arab Emirates'),
  Country('AF', 'Afghanistan'),
  Country('AG', 'Antigua and Barbuda'),
  Country('AI', 'Anguilla'),
  Country('AL', 'Albania'),
  Country('AM', 'Armenia'),
  Country('AO', 'Angola'),
  Country('AQ', 'Antarctica'),
  Country('AR', 'Argentina'),
  Country('AS', 'American Samoa'),
  Country('AT', 'Austria'),
  Country('AU', 'Australia'),
  Country('AW', 'Aruba'),
  Country('AX', 'Åland Islands'),
  Country('AZ', 'Azerbaijan'),
  Country('BA', 'Bosnia and Herzegovina'),
  Country('BB', 'Barbados'),
  Country('BD', 'Bangladesh'),
  Country('BE', 'Belgium'),
  Country('BF', 'Burkina Faso'),
  Country('BG', 'Bulgaria'),
  Country('BH', 'Bahrain'),
  Country('BI', 'Burundi'),
  Country('BJ', 'Benin'),
  Country('BL', 'Saint Barthélemy'),
  Country('BM', 'Bermuda'),
  Country('BN', 'Brunei'),
  Country('BO', 'Bolivia'),
  Country('BQ', 'Caribbean Netherlands'),
  Country('BR', 'Brazil'),
  Country('BS', 'Bahamas'),
  Country('BT', 'Bhutan'),
  Country('BV', 'Bouvet Island'),
  Country('BW', 'Botswana'),
  Country('BY', 'Belarus'),
  Country('BZ', 'Belize'),
  Country('CA', 'Canada'),
  Country('CC', 'Cocos (Keeling) Islands'),
  Country('CD', 'DR Congo'),
  Country('CF', 'Central African Republic'),
  Country('CG', 'Republic of the Congo'),
  Country('CH', 'Switzerland'),
  Country('CI', 'Ivory Coast'),
  Country('CK', 'Cook Islands'),
  Country('CL', 'Chile'),
  Country('CM', 'Cameroon'),
  Country('CN', 'China'),
  Country('CO', 'Colombia'),
  Country('CR', 'Costa Rica'),
  Country('CU', 'Cuba'),
  Country('CV', 'Cape Verde'),
  Country('CW', 'Curaçao'),
  Country('CX', 'Christmas Island'),
  Country('CY', 'Cyprus'),
  Country('CZ', 'Czechia'),
  Country('DE', 'Germany'),
  Country('DJ', 'Djibouti'),
  Country('DK', 'Denmark'),
  Country('DM', 'Dominica'),
  Country('DO', 'Dominican Republic'),
  Country('DZ', 'Algeria'),
  Country('EC', 'Ecuador'),
  Country('EE', 'Estonia'),
  Country('EG', 'Egypt'),
  Country('EH', 'Western Sahara'),
  Country('ER', 'Eritrea'),
  Country('ES', 'Spain'),
  Country('ET', 'Ethiopia'),
  Country('FI', 'Finland'),
  Country('FJ', 'Fiji'),
  Country('FK', 'Falkland Islands'),
  Country('FM', 'Micronesia'),
  Country('FO', 'Faroe Islands'),
  Country('FR', 'France'),
  Country('GA', 'Gabon'),
  Country('GB', 'United Kingdom'),
  Country('GD', 'Grenada'),
  Country('GE', 'Georgia'),
  Country('GF', 'French Guiana'),
  Country('GG', 'Guernsey'),
  Country('GH', 'Ghana'),
  Country('GI', 'Gibraltar'),
  Country('GL', 'Greenland'),
  Country('GM', 'Gambia'),
  Country('GN', 'Guinea'),
  Country('GP', 'Guadeloupe'),
  Country('GQ', 'Equatorial Guinea'),
  Country('GR', 'Greece'),
  Country('GS', 'South Georgia'),
  Country('GT', 'Guatemala'),
  Country('GU', 'Guam'),
  Country('GW', 'Guinea-Bissau'),
  Country('GY', 'Guyana'),
  Country('HK', 'Hong Kong'),
  Country('HM', 'Heard Island and McDonald Islands'),
  Country('HN', 'Honduras'),
  Country('HR', 'Croatia'),
  Country('HT', 'Haiti'),
  Country('HU', 'Hungary'),
  Country('ID', 'Indonesia'),
  Country('IE', 'Ireland'),
  Country('IL', 'Israel'),
  Country('IM', 'Isle of Man'),
  Country('IN', 'India'),
  Country('IO', 'British Indian Ocean Territory'),
  Country('IQ', 'Iraq'),
  Country('IR', 'Iran'),
  Country('IS', 'Iceland'),
  Country('IT', 'Italy'),
  Country('JE', 'Jersey'),
  Country('JM', 'Jamaica'),
  Country('JO', 'Jordan'),
  Country('JP', 'Japan'),
  Country('KE', 'Kenya'),
  Country('KG', 'Kyrgyzstan'),
  Country('KH', 'Cambodia'),
  Country('KI', 'Kiribati'),
  Country('KM', 'Comoros'),
  Country('KN', 'Saint Kitts and Nevis'),
  Country('KP', 'North Korea'),
  Country('KR', 'South Korea'),
  Country('KW', 'Kuwait'),
  Country('KY', 'Cayman Islands'),
  Country('KZ', 'Kazakhstan'),
  Country('LA', 'Laos'),
  Country('LB', 'Lebanon'),
  Country('LC', 'Saint Lucia'),
  Country('LI', 'Liechtenstein'),
  Country('LK', 'Sri Lanka'),
  Country('LR', 'Liberia'),
  Country('LS', 'Lesotho'),
  Country('LT', 'Lithuania'),
  Country('LU', 'Luxembourg'),
  Country('LV', 'Latvia'),
  Country('LY', 'Libya'),
  Country('MA', 'Morocco'),
  Country('MC', 'Monaco'),
  Country('MD', 'Moldova'),
  Country('ME', 'Montenegro'),
  Country('MF', 'Saint Martin'),
  Country('MG', 'Madagascar'),
  Country('MH', 'Marshall Islands'),
  Country('MK', 'North Macedonia'),
  Country('ML', 'Mali'),
  Country('MM', 'Myanmar'),
  Country('MN', 'Mongolia'),
  Country('MO', 'Macau'),
  Country('MP', 'Northern Mariana Islands'),
  Country('MQ', 'Martinique'),
  Country('MR', 'Mauritania'),
  Country('MS', 'Montserrat'),
  Country('MT', 'Malta'),
  Country('MU', 'Mauritius'),
  Country('MV', 'Maldives'),
  Country('MW', 'Malawi'),
  Country('MX', 'Mexico'),
  Country('MY', 'Malaysia'),
  Country('MZ', 'Mozambique'),
  Country('NA', 'Namibia'),
  Country('NC', 'New Caledonia'),
  Country('NE', 'Niger'),
  Country('NF', 'Norfolk Island'),
  Country('NG', 'Nigeria'),
  Country('NI', 'Nicaragua'),
  Country('NL', 'Netherlands'),
  Country('NO', 'Norway'),
  Country('NP', 'Nepal'),
  Country('NR', 'Nauru'),
  Country('NU', 'Niue'),
  Country('NZ', 'New Zealand'),
  Country('OM', 'Oman'),
  Country('PA', 'Panama'),
  Country('PE', 'Peru'),
  Country('PF', 'French Polynesia'),
  Country('PG', 'Papua New Guinea'),
  Country('PH', 'Philippines'),
  Country('PK', 'Pakistan'),
  Country('PL', 'Poland'),
  Country('PM', 'Saint Pierre and Miquelon'),
  Country('PN', 'Pitcairn Islands'),
  Country('PR', 'Puerto Rico'),
  Country('PS', 'Palestine'),
  Country('PT', 'Portugal'),
  Country('PW', 'Palau'),
  Country('PY', 'Paraguay'),
  Country('QA', 'Qatar'),
  Country('RE', 'Réunion'),
  Country('RO', 'Romania'),
  Country('RS', 'Serbia'),
  Country('RU', 'Russia'),
  Country('RW', 'Rwanda'),
  Country('SA', 'Saudi Arabia'),
  Country('SB', 'Solomon Islands'),
  Country('SC', 'Seychelles'),
  Country('SD', 'Sudan'),
  Country('SE', 'Sweden'),
  Country('SG', 'Singapore'),
  Country('SH', 'Saint Helena'),
  Country('SI', 'Slovenia'),
  Country('SJ', 'Svalbard and Jan Mayen'),
  Country('SK', 'Slovakia'),
  Country('SL', 'Sierra Leone'),
  Country('SM', 'San Marino'),
  Country('SN', 'Senegal'),
  Country('SO', 'Somalia'),
  Country('SR', 'Suriname'),
  Country('SS', 'South Sudan'),
  Country('ST', 'São Tomé and Príncipe'),
  Country('SV', 'El Salvador'),
  Country('SX', 'Sint Maarten'),
  Country('SY', 'Syria'),
  Country('SZ', 'Eswatini'),
  Country('TC', 'Turks and Caicos Islands'),
  Country('TD', 'Chad'),
  Country('TF', 'French Southern Territories'),
  Country('TG', 'Togo'),
  Country('TH', 'Thailand'),
  Country('TJ', 'Tajikistan'),
  Country('TK', 'Tokelau'),
  Country('TL', 'Timor-Leste'),
  Country('TM', 'Turkmenistan'),
  Country('TN', 'Tunisia'),
  Country('TO', 'Tonga'),
  Country('TR', 'Turkey'),
  Country('TT', 'Trinidad and Tobago'),
  Country('TV', 'Tuvalu'),
  Country('TW', 'Taiwan'),
  Country('TZ', 'Tanzania'),
  Country('UA', 'Ukraine'),
  Country('UG', 'Uganda'),
  Country('UM', 'U.S. Minor Outlying Islands'),
  Country('US', 'United States'),
  Country('UY', 'Uruguay'),
  Country('UZ', 'Uzbekistan'),
  Country('VA', 'Vatican City'),
  Country('VC', 'Saint Vincent and the Grenadines'),
  Country('VE', 'Venezuela'),
  Country('VG', 'British Virgin Islands'),
  Country('VI', 'U.S. Virgin Islands'),
  Country('VN', 'Vietnam'),
  Country('VU', 'Vanuatu'),
  Country('WF', 'Wallis and Futuna'),
  Country('WS', 'Samoa'),
  Country('XK', 'Kosovo'),
  Country('YE', 'Yemen'),
  Country('YT', 'Mayotte'),
  Country('ZA', 'South Africa'),
  Country('ZM', 'Zambia'),
  Country('ZW', 'Zimbabwe'),
];

// Maps for quick lookup
final _byCode = {for (final c in countries) c.code: c};
final _byNameLower = {for (final c in countries) c.name.toLowerCase(): c};

// Alternative names/spellings that map to standard codes
const _aliases = <String, String>{
  'usa': 'US',
  'united states of america': 'US',
  'america': 'US',
  'uk': 'GB',
  'england': 'GB',
  'great britain': 'GB',
  'britain': 'GB',
  'scotland': 'GB',
  'wales': 'GB',
  'northern ireland': 'GB',
  'holland': 'NL',
  'the netherlands': 'NL',
  'czech republic': 'CZ',
  'ivory coast': 'CI',
  "côte d'ivoire": 'CI',
  'south korea': 'KR',
  'korea': 'KR',
  'republic of korea': 'KR',
  'north korea': 'KP',
  'democratic republic of the congo': 'CD',
  'drc': 'CD',
  'congo': 'CG',
  'republic of the congo': 'CG',
  'uae': 'AE',
  'emirates': 'AE',
  'russia': 'RU',
  'russian federation': 'RU',
  'taiwan': 'TW',
  'republic of china': 'TW',
  'vietnam': 'VN',
  'viet nam': 'VN',
  'burma': 'MM',
  'east timor': 'TL',
  'swaziland': 'SZ',
  'macedonia': 'MK',
  'fyrom': 'MK',
  'cabo verde': 'CV',
  'vatican': 'VA',
  'holy see': 'VA',
  'brunei darussalam': 'BN',
  'lao': 'LA',
  'laos': 'LA',
  "lao people's democratic republic": 'LA',
  'syrian arab republic': 'SY',
  'iran, islamic republic of': 'IR',
  'persia': 'IR',
  'bolivia, plurinational state of': 'BO',
  'venezuela, bolivarian republic of': 'VE',
  'tanzania, united republic of': 'TZ',
  'micronesia, federated states of': 'FM',
  'moldova, republic of': 'MD',
  'palestine, state of': 'PS',
  'palestinian territory': 'PS',
  'falkland islands (malvinas)': 'FK',
  'malvinas': 'FK',
  'hong kong sar': 'HK',
  'macao': 'MO',
  'macau sar': 'MO',
  'reunion': 'RE',
  'curacao': 'CW',
  'st. lucia': 'LC',
  'st lucia': 'LC',
  'st. vincent': 'VC',
  'st vincent': 'VC',
  'st. kitts': 'KN',
  'st kitts': 'KN',
  'türkiye': 'TR',
  'turkiye': 'TR',
};

/// Look up a country by its ISO code
Country? countryByCode(String code) => _byCode[code.toUpperCase()];

/// Get the display name for a country code or freetext value.
/// If it's a valid code, returns the country name.
/// Otherwise returns the input as-is (for legacy freetext values).
String countryDisplayName(String codeOrName) {
  if (codeOrName.isEmpty) return '';
  final country = _byCode[codeOrName.toUpperCase()];
  if (country != null) return country.name;
  return codeOrName;
}

/// Try to match an input string to a country code.
/// Returns the ISO code if matched, or null if no match found.
String? matchCountryCode(String input) {
  if (input.isEmpty) return null;

  final upper = input.toUpperCase();
  final lower = input.toLowerCase();

  // Direct code match
  if (_byCode.containsKey(upper)) return upper;

  // Exact name match
  final byName = _byNameLower[lower];
  if (byName != null) return byName.code;

  // Alias match
  final alias = _aliases[lower];
  if (alias != null) return alias;

  // No match
  return null;
}

/// Normalize a country value: if it matches a known country, return the code.
/// Otherwise return the original value (for legacy freetext).
String normalizeCountry(String input) {
  if (input.isEmpty) return '';
  final code = matchCountryCode(input);
  return code ?? input;
}

/// Check if a value is a valid ISO country code
bool isCountryCode(String value) => _byCode.containsKey(value.toUpperCase());

/// Get the flag asset path for a country code.
/// Returns null if not a valid code.
String? countryFlagAsset(String codeOrName) {
  final upper = codeOrName.toUpperCase();
  if (_byCode.containsKey(upper)) {
    return 'assets/flags/${upper.toLowerCase()}.png';
  }
  return null;
}
