formatter:
  page_width: 160

linter:
  rules:
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    sort_pub_dependencies: true
    unawaited_futures: true
    unnecessary_async: true
    unnecessary_breaks: true
    unnecessary_null_checks: true
    unnecessary_statements: true
