on:
  push:
    branches:
      - main
      - release*

name: Build app

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  calver:
    name: Set version
    runs-on: ubuntu-latest
    if: github.repository == 'bubbletrail/bubbletrail'
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-tags: true
          fetch-depth: 0
      - id: calver
        uses: docker://ghcr.io/calmh/calver:latest
      - run: |
          echo "VERSION=${{ steps.calver.outputs.version }}" >> "$GITHUB_ENV"
      - id: isrelease
        if: github.repository_owner == 'bubbletrail' && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release')
        run: |
          echo release=true >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.calver.outputs.version }}
      release: ${{ steps.isrelease.outputs.release }}

  test:
    name: Run tests (app)
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable

      - name: Run tests
        run: |
          for f in pkg/btbuhlmann pkg/btcountries app ; do
            pushd $f
            flutter pub get
            flutter analyze --fatal-infos
            dart format --output=none --set-exit-if-changed $(find . -name \*.dart -not -name \*.g.dart -not -name \*.pb\*.dart)
            flutter test
            popd
          done

  build-macos:
    name: Build for macOS (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    runs-on: macos-26
    needs:
      - test
      - calver
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable

      - uses: ./.github/actions/build-info

      - name: Build & sign
        run: |
          pipx install codemagic-cli-tools
          pushd app
          ./build-macos-direct.sh
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          AZURE_MAPS_SUBSCRIPTION_KEY: ${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}
          DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_CERT }}
          MAC_APP_DISTRIBUTION_CERT: ${{ secrets.MAC_APP_DISTRIBUTION_CERT }}
          MARKET_VERSION: ${{ needs.calver.outputs.version }}

      - name: Save artifacts (macOS)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: macos
          path: app/bubbletrail*.zip
          retention-days: 1

      ## Now create and publish the appcast

      - name: install rclone
        if: needs.calver.outputs.release
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: rclone download
        if: needs.calver.outputs.release
        run: |
          rclone sync minio:updates updates
        env:
          RCLONE_CONFIG_MINIO_TYPE: ${{ secrets.RCLONE_CONFIG_MINIO_TYPE }}
          RCLONE_CONFIG_MINIO_PROVIDER: ${{ secrets.RCLONE_CONFIG_MINIO_PROVIDER }}
          RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_MINIO_ACCESS_KEY_ID }}
          RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_MINIO_REGION: ${{ secrets.RCLONE_CONFIG_MINIO_REGION }}
          RCLONE_CONFIG_MINIO_ENDPOINT: ${{ secrets.RCLONE_CONFIG_MINIO_ENDPOINT }}
          RCLONE_CONFIG_MINIO_ACL: ${{ secrets.RCLONE_CONFIG_MINIO_ACL }}

      - name: Copy new package
        if: needs.calver.outputs.release
        run: |
          cp app/bubbletrail*zip updates

      - name: Generate appcast
        if: needs.calver.outputs.release
        run: |
          cmd=$(find . -type f -name generate_appcast)
          echo "$SPARKLE_PRIVATE_KEY" | $cmd --ed-key-file - updates
        env:
          SPARKLE_PRIVATE_KEY: ${{ secrets.SPARKLE_PRIVATE_KEY }}

      - name: rclone upload
        if: needs.calver.outputs.release
        run: |
          rclone sync  -v --no-update-modtime updates minio:updates
        env:
          RCLONE_CONFIG_MINIO_TYPE: ${{ secrets.RCLONE_CONFIG_MINIO_TYPE }}
          RCLONE_CONFIG_MINIO_PROVIDER: ${{ secrets.RCLONE_CONFIG_MINIO_PROVIDER }}
          RCLONE_CONFIG_MINIO_ACCESS_KEY_ID: ${{ secrets.RCLONE_CONFIG_MINIO_ACCESS_KEY_ID }}
          RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY: ${{ secrets.RCLONE_CONFIG_MINIO_SECRET_ACCESS_KEY }}
          RCLONE_CONFIG_MINIO_REGION: ${{ secrets.RCLONE_CONFIG_MINIO_REGION }}
          RCLONE_CONFIG_MINIO_ENDPOINT: ${{ secrets.RCLONE_CONFIG_MINIO_ENDPOINT }}
          RCLONE_CONFIG_MINIO_ACL: ${{ secrets.RCLONE_CONFIG_MINIO_ACL }}

  build-ios:
    name: Build for iOS (Appstore) (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    runs-on: macos-26
    needs:
      - test
      - calver
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable

      - uses: ./.github/actions/build-info

      - name: Build
        run: |
            cd app
            flutter pub get
            flutter build ipa \
                --release --no-pub --no-codesign \
                --build-number="$BUILD_NUMBER" \
                --build-name="${{ needs.calver.outputs.version }}" \
                --dart-define=AZURE_MAPS_SUBSCRIPTION_KEY="$AZURE_MAPS_SUBSCRIPTION_KEY" \
                --dart-define=BUILD="$BUILD_NUMBER" \
                --dart-define=BUILDSECONDS="$SOURCE_DATE_EPOCH" \
                --dart-define=GITSHA="$GIT_SHA" \
                --dart-define=MARKETINGVERSION="${{ needs.calver.outputs.version }}"
        env:
          AZURE_MAPS_SUBSCRIPTION_KEY: ${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}

      - name: Push to AppStore
        if: needs.calver.outputs.release
        run: |
            security create-keychain -p $MATCH_KEYCHAIN_PASSWORD $MATCH_KEYCHAIN_NAME
            security unlock-keychain -p $MATCH_KEYCHAIN_PASSWORD $MATCH_KEYCHAIN_NAME
            security set-keychain-settings -lut 21600 $MATCH_KEYCHAIN_NAME
            security default-keychain -d user -s $MATCH_KEYCHAIN_NAME

            cd app/ios
            fastlane push
        env:
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_KEYCHAIN_NAME: ${{ runner.temp }}/bubbletrain.keychain
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}


  build-windows:
    name: Build for Windows (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    runs-on: windows-latest
    needs:
      - test
      - calver
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable

      - uses: ./.github/actions/build-info

      - name: Build Windows executable
        shell: bash
        run: |
          cd app
          flutter pub get
          flutter build windows \
              --release --no-pub \
              --build-number="$BUILD_NUMBER" \
              --build-name="${{ needs.calver.outputs.version }}" \
              --dart-define=AZURE_MAPS_SUBSCRIPTION_KEY="$AZURE_MAPS_SUBSCRIPTION_KEY" \
              --dart-define=BUILD="$BUILD_NUMBER" \
              --dart-define=BUILDSECONDS="$SOURCE_DATE_EPOCH" \
              --dart-define=GITSHA="$GIT_SHA" \
              --dart-define=MARKETINGVERSION="${{ needs.calver.outputs.version }}"
        env:
          AZURE_MAPS_SUBSCRIPTION_KEY: ${{ secrets.AZURE_MAPS_SUBSCRIPTION_KEY }}

      - name: Sign files with Trusted Signing
        uses: azure/trusted-signing-action@c7ab2a863ab5f9a846ddb8265964877ef296ee82 # v2.0.0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TRUSTED_SIGNING_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_TRUSTED_SIGNING_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_TRUSTED_SIGNING_CLIENT_SECRET }}
          endpoint: ${{ secrets.AZURE_TRUSTED_SIGNING_ENDPOINT }}
          trusted-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT }}
          certificate-profile-name: ${{ secrets.AZURE_TRUSTED_SIGNING_PROFILE }}
          files-folder: ${{ github.workspace }}\app\build\windows\x64\runner\Release
          files-folder-filter: exe
          files-folder-recurse: true
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Package Windows build
        shell: pwsh
        run: |
          cd app
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath "bubbletrail-windows-${{ needs.calver.outputs.version }}-$env:BUILD_NUMBER.zip"

      - name: Save artifacts (Windows)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows
          path: app/bubbletrail*.zip
          retention-days: 1

  build-android:
    name: Build for Android (Play Store) (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    runs-on: ubuntu-latest
    needs:
      - test
      - calver
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2
        with:
          channel: stable

      - uses: ./.github/actions/build-info

      - name: Build
        run: |
            cd app

            echo "$ANDROID_KEY_PROPERTIES" > android/key.properties
            echo "$ANDROID_UPLOAD_KEYSTORE" | base64 -d > android/app/upload-keystore.jks

            flutter pub get
            flutter build appbundle \
                --release --no-pub \
                --build-number="$BUILD_NUMBER" \
                --build-name="${{ needs.calver.outputs.version }}" \
                --dart-define=AZURE_MAPS_SUBSCRIPTION_KEY="$AZURE_MAPS_SUBSCRIPTION_KEY" \
                --dart-define=BUILD="$BUILD_NUMBER" \
                --dart-define=BUILDSECONDS="$SOURCE_DATE_EPOCH" \
                --dart-define=GITSHA="$GIT_SHA" \
                --dart-define=MARKETINGVERSION="${{ needs.calver.outputs.version }}"

            mv build/app/outputs/bundle/release/app-release.aab \
              bubbletrail-android-${{ needs.calver.outputs.version }}-$BUILD_NUMBER.aab
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}
          ANDROID_UPLOAD_KEYSTORE: ${{ secrets.ANDROID_UPLOAD_KEYSTORE }}

      - name: Save artifacts (Android)
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: android
          path: app/bubbletrail*.aab

      - uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1
        if: needs.calver.outputs.release
        with:
          ruby-version: 3.3.8
          bundler-cache: true
          working-directory: app/android

      - name: Push to Google Play
        if: needs.calver.outputs.release
        shell: bash
        run: |
          cd app/android
          mv ../bubbletrail-android-${{ needs.calver.outputs.version }}-$BUILD_NUMBER.aab app-release.aab
          echo "$GOOGLE_PLAY_API_KEY_JSON" > fastlane/apikey.json
          bundle exec fastlane deploy
        env:
          GOOGLE_PLAY_API_KEY_JSON: ${{ secrets.GOOGLE_PLAY_API_KEY_JSON }}

  publish-release:
    name: Publish GitHub release (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    if: needs.calver.outputs.release && github.ref == 'refs/heads/release'
    permissions:
      contents: write
    needs:
      - build-macos
      - build-windows
      - calver
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: dart-lang/setup-dart@65eb853c7ba17dde3be364c3d2858773e7144260 # v1
      - uses: ./.github/actions/build-info

      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: packages
          merge-multiple: true

      - name: Push binaries to GitHub release
        run: |
          export GH_PROMPT_DISABLED=1
          tag="v${{ needs.calver.outputs.version }}"

          gh release create "$tag" \
              --draft \
              --title "$tag" \
              --generate-notes

          gh release upload "$tag" packages/*.zip
          gh release edit "$tag" --draft=false
        env:
          GH_TOKEN: ${{ github.token }}

  build-server:
    name: Build & test admin server (${{ needs.calver.outputs.version}} ${{ github.run_number }})
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs:
      - calver
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: stable

      - name: Run tests
        run: |
          pushd srv
          go test ./...

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d # v0.9

      - name: Log in to GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        run: |
          pushd srv
          ko build --bare --sbom=none \
            -t latest \
            -t "${{ needs.calver.outputs.version }}" \
            -t "${{ github.run_number }}" .
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}-admin-srv
